jenkins:
  container_name: jenkins
  image: jenkins
  user: root
  ports:
      - "8080:8080"
  volumes:
    - ~/jenkins/:/var/jenkins_home
  restart: always


docker:
  container_name: jenkins_docker
  image: docker:1.8-dind
  privileged: true
  links:
    - jenkins
